# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
wally = "UpliftGames/wally@0.3.2"
rojo = "UpliftGames/rojo@7.3.0-uplift.11"
wally-package-types = "JohnnyMorganz/wally-package-types@1.2.1"
StyLua = "JohnnyMorganz/StyLua@0.18.0"
# rojo = "rojo-rbx/rojo@6.2.0"